apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - pvc-data.yaml
  - services.yaml
  - stateful.yaml
  - deployments.yaml
  - ingress.yaml
configMapGenerator:
  - name: auto-dev-proxy-ca
    namespace: autodev
    files:
      - amgen-proxy-ca.crt=local/amgen-proxy-chain.pem
generatorOptions:
  disableNameSuffixHash: true
